export const CONSTANTS = { SITE_TITLE: "YTHWKND",
  SITE_SUBTITLE: "AND THE",
  SITE_MAIN_TITLE: "MULTIVERSE OF MYSTERY",
  SITE_DESCRIPTION: "A HIGHSCHOOL EVENT BY @YMFGAKL",

  // Hero options with updated names, classes, perks and new images
  HEROES: [
    {
      id: "alex",
      name: "Alex Huntington",
      icon: "/alex-huntington.png",
      class: "THE LEADER",
      perk: "HALL PASS OF HASTE",
      description:
        "Grants your team early movement and extra time.",
    },
    {
      id: "suzzy",
      name: "Suzzy Prasad",
      icon: "/suzzy-prasad.png",
      class: "THE ENGINEER",
      perk: "SCHOLAR'S BOUNTY",
      description:
        "Doubles your team's score like a bonus assignment",
    },
    {
      id: "charlotte",
      name: "Charlotte Mayfield",
      icon: "/charlotte-mayfield.png",
      class: "THE TWIN HEALER",
      perk: "NOTE OF RENEWAL",
      description:
        "Revives your team back together for a fresh start.",
    },
    {
      id: "charlie",
      name: "Charlie Mayfield",
      icon: "/charlie-mayfield.png",
      class: "THE TWIN TANKER",
      perk: "SEAL OF DETENTION",
      description:
        "Cancels any perks your enemy has chosen.",
    },
    {
      id: "kai",
      name: "Kai",
      icon: "/kai.png",
      class: "WILDCARD",
      perk: "SKIBIDI",
      description:
        "Dealbreaker to change the odds of the game.",
    },
  ],

  // Team options (using the 20 teams we created)
  TEAMS: [
    { id: 1, name: "The Original Five", color: "bg-team-01", code: "U001" },
    { id: 2, name: "The Shrek Five", color: "bg-team-02", code: "U002" },
    { id: 3, name: "The Powerpuff Five", color: "bg-team-03", code: "U003" },
    { id: 4, name: "The Real Five", color: "bg-team-04", code: "U004" },
    { id: 5, name: "The Funko Five", color: "bg-team-05", code: "U005" },
    { id: 6, name: "The Spider Five", color: "bg-team-06", code: "U006" },
    { id: 7, name: "The Panda Five", color: "bg-team-07", code: "U007" },
    { id: 8, name: "The Little Miss Five", color: "bg-team-08", code: "U008" },
    { id: 9, name: "The Conan Five", color: "bg-team-09", code: "U009" },
    { id: 10, name: "The Minion Five", color: "bg-team-10", code: "U010" },
    { id: 11, name: "The Lego Five", color: "bg-team-11", code: "U011" },
    { id: 12, name: "The Avengers Five", color: "bg-team-12", code: "U012" },
    { id: 13, name: "The Smurfed Five", color: "bg-team-13", code: "U013" },
    { id: 14, name: "The Minecraft Five", color: "bg-team-14", code: "U014" },
    { id: 15, name: "The Clay Five", color: "bg-team-15", code: "U015" },
    { id: 16, name: "The Barbie Five", color: "bg-team-16", code: "U016" },
    { id: 17, name: "The 8 bit Five", color: "bg-team-17", code: "U017" },
    { id: 18, name: "The Quest Five", color: "bg-team-18", code: "U018" },
    { id: 19, name: "The Future Five", color: "bg-team-19", code: "U019" },
    { id: 20, name: "The Steampunk Five", color: "bg-team-20", code: "U020" },
  ],

  HERO_IMAGE_PATHS: [
    { teamId: 1, hero: "Alex", path: "/hundred/001_Original-Five_01-Alex.png" },
    {
      teamId: 1,
      hero: "Suzzy",
      path: "/hundred/001_Original-Five_02-Suzzy.png",
    },
    {
      teamId: 1,
      hero: "Charlotte",
      path: "/hundred/001_Original-Five_03-Charlotte.png",
    },
    {
      teamId: 1,
      hero: "Charlie",
      path: "/hundred/001_Original-Five_04-Charlie.png",
    },
    { teamId: 1, hero: "Kai", path: "/hundred/001_Original-Five_05-Kai.png" },
    { teamId: 2, hero: "Alex", path: "/hundred/002_Shrek-Five_01-Alex.png" },
    { teamId: 2, hero: "Suzzy", path: "/hundred/002_Shrek-Five_02-Suzzy.png" },
    {
      teamId: 2,
      hero: "Charlotte",
      path: "/hundred/002_Shrek-Five_03-Charlotte.png",
    },
    {
      teamId: 2,
      hero: "Charlie",
      path: "/hundred/002_Shrek-Five_04-Charlie.png",
    },
    { teamId: 2, hero: "Kai", path: "/hundred/002_Shrek-Five_05-Kai.png" },
    {
      teamId: 3,
      hero: "Alex",
      path: "/hundred/003_Powerpuff-Five_01-Alex.png",
    },
    {
      teamId: 3,
      hero: "Suzzy",
      path: "/hundred/003_Powerpuff-Five_02-Suzzy.png",
    },
    {
      teamId: 3,
      hero: "Charlotte",
      path: "/hundred/003_Powerpuff-Five_03-Charlotte.png",
    },
    {
      teamId: 3,
      hero: "Charlie",
      path: "/hundred/003_Powerpuff-Five_04-Charlie.png",
    },
    { teamId: 3, hero: "Kai", path: "/hundred/003_Powerpuff-Five_05-Kai.png" },
    { teamId: 4, hero: "Alex", path: "/hundred/004_Real-Five_01-Alex.png" },
    { teamId: 4, hero: "Suzzy", path: "/hundred/004_Real-Five_02-Suzzy.png" },
    {
      teamId: 4,
      hero: "Charlotte",
      path: "/hundred/004_Real-Five_03-Charlotte.png",
    },
    {
      teamId: 4,
      hero: "Charlie",
      path: "/hundred/004_Real-Five_04-Charlie.png",
    },
    { teamId: 4, hero: "Kai", path: "/hundred/004_Real-Five_05-Kai.png" },
    { teamId: 5, hero: "Alex", path: "/hundred/005_Funko-Five_01-Alex.png" },
    { teamId: 5, hero: "Suzzy", path: "/hundred/005_Funko-Five_02-Suzzy.png" },
    {
      teamId: 5,
      hero: "Charlotte",
      path: "/hundred/005_Funko-Five_03-Charlotte.png",
    },
    {
      teamId: 5,
      hero: "Charlie",
      path: "/hundred/005_Funko-Five_04-Charlie.png",
    },
    { teamId: 5, hero: "Kai", path: "/hundred/005_Funko-Five_05-Kai.png" },
    { teamId: 6, hero: "Alex", path: "/hundred/006_Spider-Five_01-Alex.png" },
    { teamId: 6, hero: "Suzzy", path: "/hundred/006_Spider-Five_02-Suzzy.png" },
    {
      teamId: 6,
      hero: "Charlotte",
      path: "/hundred/006_Spider-Five_03-Charlotte.png",
    },
    {
      teamId: 6,
      hero: "Charlie",
      path: "/hundred/006_Spider-Five_04-Charlie.png",
    },
    { teamId: 6, hero: "Kai", path: "/hundred/006_Spider-Five_05-Kai.png" },
    { teamId: 7, hero: "Alex", path: "/hundred/007_Panda-Five_01-Alex.png" },
    { teamId: 7, hero: "Suzzy", path: "/hundred/007_Panda-Five_02-Suzzy.png" },
    {
      teamId: 7,
      hero: "Charlotte",
      path: "/hundred/007_Panda-Five_03-Charlotte.png",
    },
    {
      teamId: 7,
      hero: "Charlie",
      path: "/hundred/007_Panda-Five_04-Charlie.png",
    },
    { teamId: 7, hero: "Kai", path: "/hundred/007_Panda-Five_05-Kai.png" },
    {
      teamId: 8,
      hero: "Alex",
      path: "/hundred/008_Little-Miss-Five_01-Alex.png",
    },
    {
      teamId: 8,
      hero: "Suzzy",
      path: "/hundred/008_Little-Miss-Five_02-Suzzy.png",
    },
    {
      teamId: 8,
      hero: "Charlotte",
      path: "/hundred/008_Little-Miss-Five_03-Charlotte.png",
    },
    {
      teamId: 8,
      hero: "Charlie",
      path: "/hundred/008_Little-Miss-Five_04-Charlie.png",
    },
    {
      teamId: 8,
      hero: "Kai",
      path: "/hundred/008_Little-Miss-Five_05-Kai.png",
    },
    { teamId: 9, hero: "Alex", path: "/hundred/009_Conan-Five_01-Alex.png" },
    { teamId: 9, hero: "Suzzy", path: "/hundred/009_Conan-Five_02-Suzzy.png" },
    {
      teamId: 9,
      hero: "Charlotte",
      path: "/hundred/009_Conan-Five_03-Charlotte.png",
    },
    {
      teamId: 9,
      hero: "Charlie",
      path: "/hundred/009_Conan-Five_04-Charlie.png",
    },
    { teamId: 9, hero: "Kai", path: "/hundred/009_Conan-Five_05-Kai.png" },
    { teamId: 10, hero: "Alex", path: "/hundred/010_Minion-Five_01-Alex.png" },
    {
      teamId: 10,
      hero: "Suzzy",
      path: "/hundred/010_Minion-Five_02-Suzzy.png",
    },
    {
      teamId: 10,
      hero: "Charlotte",
      path: "/hundred/010_Minion-Five_03-Charlotte.png",
    },
    {
      teamId: 10,
      hero: "Charlie",
      path: "/hundred/010_Minion-Five_04-Charlie.png",
    },
    { teamId: 10, hero: "Kai", path: "/hundred/010_Minion-Five_05-Kai.png" },
    { teamId: 11, hero: "Alex", path: "/hundred/011_Lego-Five_01-Alex.png" },
    { teamId: 11, hero: "Suzzy", path: "/hundred/011_Lego-Five_02-Suzzy.png" },
    {
      teamId: 11,
      hero: "Charlotte",
      path: "/hundred/011_Lego-Five_03-Charlotte.png",
    },
    {
      teamId: 11,
      hero: "Charlie",
      path: "/hundred/011_Lego-Five_04-Charlie.png",
    },
    { teamId: 11, hero: "Kai", path: "/hundred/011_Lego-Five_05-Kai.png" },
    {
      teamId: 12,
      hero: "Alex",
      path: "/hundred/012_Avengers-Five_01-Alex.png",
    },
    {
      teamId: 12,
      hero: "Suzzy",
      path: "/hundred/012_Avengers-Five_02-Suzzy.png",
    },
    {
      teamId: 12,
      hero: "Charlotte",
      path: "/hundred/012_Avengers-Five_03-Charlotte.png",
    },
    {
      teamId: 12,
      hero: "Charlie",
      path: "/hundred/012_Avengers-Five_04-Charlie.png",
    },
    { teamId: 12, hero: "Kai", path: "/hundred/012_Avengers-Five_05-Kai.png" },
    { teamId: 13, hero: "Alex", path: "/hundred/013_Smurfed-Five_01-Alex.png" },
    {
      teamId: 13,
      hero: "Suzzy",
      path: "/hundred/013_Smurfed-Five_02-Suzzy.png",
    },
    {
      teamId: 13,
      hero: "Charlotte",
      path: "/hundred/013_Smurfed-Five_03-Charlotte.png",
    },
    {
      teamId: 13,
      hero: "Charlie",
      path: "/hundred/013_Smurfed-Five_04-Charlie.png",
    },
    { teamId: 13, hero: "Kai", path: "/hundred/013_Smurfed-Five_05-Kai.png" },
    {
      teamId: 14,
      hero: "Alex",
      path: "/hundred/014_Minecraft-Five_01-Alex.png",
    },
    {
      teamId: 14,
      hero: "Suzzy",
      path: "/hundred/014_Minecraft-Five_02-Suzzy.png",
    },
    {
      teamId: 14,
      hero: "Charlotte",
      path: "/hundred/014_Minecraft-Five_03-Charlotte.png",
    },
    {
      teamId: 14,
      hero: "Charlie",
      path: "/hundred/014_Minecraft-Five_04-Charlie.png",
    },
    { teamId: 14, hero: "Kai", path: "/hundred/014_Minecraft-Five_05-Kai.png" },
    { teamId: 15, hero: "Alex", path: "/hundred/015_Clay-Five_01-Alex.png" },
    { teamId: 15, hero: "Suzzy", path: "/hundred/015_Clay-Five_02-Suzzy.png" },
    {
      teamId: 15,
      hero: "Charlotte",
      path: "/hundred/015_Clay-Five_03-Charlotte.png",
    },
    {
      teamId: 15,
      hero: "Charlie",
      path: "/hundred/015_Clay-Five_04-Charlie.png",
    },
    { teamId: 15, hero: "Kai", path: "/hundred/015_Clay-Five_05-Kai.png" },
    { teamId: 16, hero: "Alex", path: "/hundred/016_Barbie-Five_01-Alex.png" },
    {
      teamId: 16,
      hero: "Suzzy",
      path: "/hundred/016_Barbie-Five_02-Suzzy.png",
    },
    {
      teamId: 16,
      hero: "Charlotte",
      path: "/hundred/016_Barbie-Five_03-Charlotte.png",
    },
    {
      teamId: 16,
      hero: "Charlie",
      path: "/hundred/016_Barbie-Five_04-Charlie.png",
    },
    { teamId: 16, hero: "Kai", path: "/hundred/016_Barbie-Five_05-Kai.png" },
    { teamId: 17, hero: "Alex", path: "/hundred/017_8-bit-Five_01-Alex.png" },
    { teamId: 17, hero: "Suzzy", path: "/hundred/017_8-bit-Five_02-Suzzy.png" },
    {
      teamId: 17,
      hero: "Charlotte",
      path: "/hundred/017_8-bit-Five_03-Charlotte.png",
    },
    {
      teamId: 17,
      hero: "Charlie",
      path: "/hundred/017_8-bit-Five_04-Charlie.png",
    },
    { teamId: 17, hero: "Kai", path: "/hundred/017_8-bit-Five_05-Kai.png" },
    { teamId: 18, hero: "Alex", path: "/hundred/018_Quest-Five_01-Alex.png" },
    { teamId: 18, hero: "Suzzy", path: "/hundred/018_Quest-Five_02-Suzzy.png" },
    {
      teamId: 18,
      hero: "Charlotte",
      path: "/hundred/018_Quest-Five_03-Charlotte.png",
    },
    {
      teamId: 18,
      hero: "Charlie",
      path: "/hundred/018_Quest-Five_04-Charlie.png",
    },
    { teamId: 18, hero: "Kai", path: "/hundred/018_Quest-Five_05-Kai.png" },
    { teamId: 19, hero: "Alex", path: "/hundred/019_Future-Five_01-Alex.png" },
    {
      teamId: 19,
      hero: "Suzzy",
      path: "/hundred/019_Future-Five_02-Suzzy.png",
    },
    {
      teamId: 19,
      hero: "Charlotte",
      path: "/hundred/019_Future-Five_03-Charlotte.png",
    },
    {
      teamId: 19,
      hero: "Charlie",
      path: "/hundred/019_Future-Five_04-Charlie.png",
    },
    { teamId: 19, hero: "Kai", path: "/hundred/019_Future-Five_05-Kai.png" },
    {
      teamId: 20,
      hero: "Alex",
      path: "/hundred/020_Steampunk-Five_01-Alex.png",
    },
    {
      teamId: 20,
      hero: "Suzzy",
      path: "/hundred/020_Steampunk-Five_02-Suzzy.png",
    },
    {
      teamId: 20,
      hero: "Charlotte",
      path: "/hundred/020_Steampunk-Five_03-Charlotte.png",
    },
    {
      teamId: 20,
      hero: "Charlie",
      path: "/hundred/020_Steampunk-Five_04-Charlie.png",
    },
    { teamId: 20, hero: "Kai", path: "/hundred/020_Steampunk-Five_05-Kai.png" },
  ],
  // Updated CG Leaders based on the design
  CG_LEADERS: [
    "Annabelle Foo",
    "Axel Chong",
    "Christopher & Oscar",
    "Clarice Low",
    "David Tiah",
    "Fanna Tan",
    "Japheth",
    "Jessica Lee",
    "Jonathan Yee",
    "Joshua Yap",
    "Kujeyna",
    "Le Shiuan",
    "May Jee",
    "Rachel Anne",
    "Samantha Edwin",
    "Yae-Ber Neo",
  ],

  // Mock ages for demo
  MOCK_AGES: [13, 14, 15, 16, 17],
};
